### ISSUE TITLE
Assigning a User to a Project Results in Assignment to All Projects and Not Being Unassigned in v0.10.4

### ISSUE THREAD

**Issue by davidblancolf** [vstruhar/lara-collab#10]
When attempting to add a user to a specific project, the user is being assigned to all projects instead. This behavior is not expected and needs to be corrected.

Steps to Reproduce:

Navigate to the project management section.
Select a specific project.
Add a user to the selected project.
Observe that the user is added to all projects instead of just the selected project.
Expected Behavior:
The user should only be assigned to the selected project and not to all projects.

Actual Behavior:
The user is assigned to all projects regardless of the specific project selection.

Impact:
This issue affects the accuracy of project assignments and may lead to unauthorized access to project information.

**Comment by vstruhar** [comment]
Hi @davidblancolf, thanks for submitting issues/bugs that you have encountered in this project. I will go trough them asap!
