### ISSUE TITLE
In Develop Mode i can create my proyects

### ISSUE THREAD

**Issue by CeicaIFCD0112** [vstruhar/lara-collab#14]
Hello Lara-Collab Team, I am grateful to you for generating this fabulous code, but I have to report some errors or crashes that I am experiencing:

1.- when it is in session and Develop mode or modal, you create a new project and then you cannot view it until your superior approves it.

2.- in develop mode you cannot create tasks, users and other functions, you have to be elevated in the roles you play

3.- in develop mode you cannot view the content of the users immersed in the platform

If any errors, reports and other elements arise, I will comment and create future reports.

Kind regards

**Comment by vstruhar** [comment]
Hi @CeicaIFCD0112, thanks for submitting this issue. I will check it asap.

**Comment by vstruhar** [comment]
Not sure about issue 2 and 3, @CeicaIFCD0112 can you add steps to reproduce?

**Comment by CeicaIFCD0112** [comment]
Thanks for your response, i dont get access to the platform, i am outside of my country,  and the company stay in vacations,  i will contact soonly
