### ISSUE TITLE
Client User Avatars Broken

### ISSUE THREAD

**Issue by ghost** [vstruhar/lara-collab#21]
Hi folks - reporting a bug related to client avatars.

**Description**
When viewing Clients > Users > Edit Client, if you proceed to upload an avatar, the image doesn't appear on page save, or after page reload, and instead defaults back to the generated initials. It's currently not possible to upload avatars for client users.

I am using local storage, (as defined in my .env file as `FILESYSTEM_DISK=local` and then setting `sail artisan storage:link`). I can see that the file does actually get uploaded and stored, but Laravel is always defaulting to showing the user initials, even though the .jpg file persists in storage.

I am using Laravel Sail and MySQL for local development on MacOS.

**Comment by vstruhar** [comment]
Thanks for reporting this issue, just pushed a fix for this!
