### ISSUE TITLE
task Board Does Not Automatically Refresh After Editing a Task

### ISSUE THREAD

**Issue by davidblancolf** [vstruhar/lara-collab#23]
I have noticed an issue with the task board functionality. When we edit a task and save the changes, the task board does not automatically update to reflect these changes. Instead, we have to manually refresh the page to see the updates, which can disrupt the workflow and reduce efficiency.

Steps to Reproduce:

Go to the task board.
Select a task to edit.
Make changes to the task (e.g., update the status or description).
Save the changes.
Observe that the task board does not automatically refresh to show the updated task information.
Expected Behavior:

After saving changes to a task, the task board should automatically refresh to display the updated task details without requiring a manual page refresh.
Proposed Solution:

Implement a real-time update mechanism or automatic refresh for the task board whenever a task is edited and saved.
Consider using technologies like WebSockets or AJAX polling to ensure the task board stays up-to-date with the latest task information.
Benefits:

Improves user experience by providing immediate feedback and updates.
Enhances productivity by reducing the need for manual page refreshes.
Ensures that all users have access to the most current task information.
Please let me know if you need any further information or if I can assist with testing this feature once implemented.

**Comment by vstruhar** [comment]
Web sockets are already implemented for realtime task and task group updates. But it won't work right out of the box, first you need to setup Pusher, see the [docs](https://github.com/vstruhar/lara-collab?tab=readme-ov-file#web-sockets) and also if your `QUEUE_CONNECTION` is not set to sync in your .env you will need to run a worker.

For more details see [useWebSockets.js](https://github.com/vstruhar/lara-collab/blob/main/resources/js/hooks/useWebSockets.js#L31) hook.
