### ISSUE TITLE
 Filtering Issues in "Daily Logged Time" Report

### ISSUE THREAD

**Issue by davidblancolf** [vstruhar/lara-collab#24]
Description
We are experiencing issues with the filtering functionality in the "Daily logged time" report. There are two specific scenarios where the filters do not return expected results.

Steps to Reproduce
Scenario 1: User and Date Range Filtering (without Billable and Completed)

Select a user.
Choose a date range.
Do not select the "Billable" and "Completed" options.
Expected Result: The report should display all logged times for the selected user and date range.
Actual Result: No results are returned.
Scenario 2: User, Date Range, and Completed Tasks Filtering

Select a user.
Choose a date range.
Select the "Completed" option.
Expected Result: The report should display all completed tasks for the selected user and date range.
Actual Result: Completed tasks are not displayed.

**Comment by vstruhar** [comment]
There could be some confusion on how and what billable and completed checkboxes mean, same as on the issue #25
