### ISSUE TITLE
Filtering Issues in "Logged Time Sum" Report

### ISSUE THREAD

**Issue by davidblancolf** [vstruhar/lara-collab#25]
Description
We are experiencing issues with the filtering functionality in the "Logged time sum" report. Specifically, when attempting to filter by a single user, the report does not return the expected results.

Steps to Reproduce
Go to the "Logged time sum" report.
Select a specific user from the user dropdown menu.
Leave other filters (e.g., date range, billable, completed) unselected.
Expected Result: The report should display the total logged time for the selected user.
Actual Result: The report does not return any results, or it returns incorrect data that does not match the selected user.

**Comment by vstruhar** [comment]
I wasn't able to reproduce reported issue, maybe there was a confusion of how it should work.
The completed checkbox will filter out tasks that are marked as completed (green checkbox in the task title), not moved to the "Done" task group.
Billed checkbox will filter out only tasks that have been set as billable.
If no date range is selected it will use the last 7 days.
