### ISSUE TITLE
 Error 500 When Adding User Email with Non-Existent Domain

### ISSUE THREAD

**Issue by davidblancolf** [vstruhar/lara-collab#26]
We are encountering a problem where attempting to add a user with an email address that has a non-existent domain results in a server error (HTTP 500). This issue should be handled more gracefully, with appropriate validation and error messaging.

Steps to Reproduce
Navigate to the user management section.
Add a new user with an email address that uses a non-existent domain (e.g., user@nonexistentdomain.com).
Submit the form.
Expected Result: The application should validate the email domain and provide a user-friendly error message indicating that the domain does not exist.
Actual Result: The application throws an HTTP 500 server error, resulting in an unhandled exception.

![image](https://github.com/user-attachments/assets/81016814-26ca-4f10-8d9d-b7c9224d62cf)

**Comment by vstruhar** [comment]
Updated email validation, this should fix the error
