### ISSUE TITLE
[Improvement] Consider upgrading to Laravel 11

### ISSUE THREAD

**Issue by refacta** [vstruhar/lara-collab#28]
Hi @vstruhar - you're undoubtedly aware of the release of Laravel 11 earlier this year, and wanted to understand your intentions, if any, towards upgrading Lara Collab to be compatible with Laravel 11. Is this an item on your near term roadmap, or is upgrading not being considered at this time?

Out of my own curiosity, I actually ran Lara Collab through [Laravel Shift's](https://laravelshift.com/) upgrade tool - while LS did make a lot of adjustments, and detailed everything with neat individual commits to a separate branch, I was sadly unable to run LC successfully in a v11 environment. While LS does do a lot of the grunt work, there's still some manual tasks required, and I don't come from a Laravel or React background, so stumbled to run the project. But I dare say a more proficient dev would have succeeded.

I also ran LC through Laravel Shift's [Fixer](https://laravelshift.com/laravel-code-fixer) tool - this again returned a separate branched version with various code improvements - Fixer isn't related to upgrading to Laravel 11, but rather just code improvements for your current version of Laravel.

Although Laravel Shift's tools are premium services, I'd be happy to share the two branches, should you want them - maybe this would be an interesting exercise for you, regardless of your intentions to upgrade or not. Just let me know. 

In any case, many thanks for a great project.

**Comment by vstruhar** [comment]
Hi @refacta, I'm aware of Laravel version 11 and I'm planning to upgrade when I have the time. When I was working on this project I didn't have time to add automated tests, so after upgrade will have to manually test everything, that's the main reason why I haven't upgraded yet.

Sure, that would be great! You can create PR and I will check it, it will definitely speed things up.

**Comment by vstruhar** [comment]
Updated to Laravel 11 - PR #29
