### ISSUE TITLE
ANY_VALUE issue mariandb

### ISSUE THREAD

**Issue by jouniikaheimo** [vstruhar/lara-collab#4]
I know that changing this feature can be difficult, but mariandb does not support ANY_VALUE functio, so if it is possible to solve this incompatibility problem, that would be great

**Comment by vstruhar** [comment]
@jouniikaheimo pushed a fix for this, replaced ANY_VALUE with MAX, so it should work with mariadb now.
Please let me know if it's fixed so I close this issue, thanks!
