### ISSUE TITLE
Always show 404

### ISSUE THREAD

**Issue by core45** [vstruhar/lara-collab#8]
On my dev laptop I wanted to try Lara Collab but after the installation I always get 404.

I use Laravel Herd and every other Laravel project works just fine.

What I did is:
1. I cloned the repo
2. npm install && npm run build
3. composer install
4. cp .env.example .env
5. migrate with seed
6. key generate

When I try to open the http://lara-collab.test site in the browser I get Laravel's 404 error page.
I tried  php artisan serve instead of Herd - all the same.

I use PHP8.3 and MySQL on M1 MacBook

**Comment by vstruhar** [comment]
Hi, I noticed I forgot to redirect to dashboard (if not authenticated to login).
Added a [fix](https://github.com/vstruhar/lara-collab/commit/0a23ccf8b12aca62e85813d2fd074ef519490818) to redirect when root url is opened.
