### ISSUE TITLE
Unable to add manual time

### ISSUE THREAD

**Issue by Abdulcomsian** [vstruhar/lara-collab#9]
Manual time + icon is disable, can you please guide on how we can allow user to add manual time as well (instead of tracking time for task).

Thanks

**Comment by vstruhar** [comment]
You just need to enter a number where time is shown, for example 1.5 or 1:30 if you want to log one hour and thirty minutes.

![how to manually log time](https://github.com/vstruhar/lara-collab/assets/6599021/102ffe2d-8b53-4c9b-852e-6d3a6e809f01)

**Comment by Abdulcomsian** [comment]
@vstruhar
Thanks alot, sorry i missed it, 

Thanks for your contribution, i am testing/reviewing it and might use it for my agency.

**Comment by vstruhar** [comment]
Great! I could improve UX by adding some tooltip or something so it's more obvious. Will see if more people will have the same issue.
